# Generated by Django 4.2.7 on 2023-11-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_images_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
