# Generated by Django 4.2.7 on 2023-11-18 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_qunatity_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complite',
            new_name='complete',
        ),
    ]
